Replace deprecated ui config option with ui_config
saltstack-formulas/consul-formula pull request #51
Opened 2020-12-10 13:17 UTC by phoerious

### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?

Consul 1.9.0 deprecates the `ui` config option, which is now replaced by `ui_config.enabled`.

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

Yes. This cannot be updated in a non-breaking fashion, but I chose the least disruptive route.

If both `ui` and `ui_config.enabled` are set , `ui_config` takes precedence. Hence, my change may enable the UI on machines which had previously set `ui` to `false`. This is arguably better than defaulting to `false`, which would disable the UI where it is supposed to be enabled.

Removing the option entirely breaks similarly if users rely on the formula defaults, since Consul's default is `false` and the formula's default used to be `true`.

### Describe the changes you're proposing

The pillar `defaults.yaml` set `ui: true` by default, which adds redundant and potentially contradicting configuration to Consul agents with the new `ui_config` option.

I also updated the ancient default Consul version to 1.9.0 appropriately.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

2020-12-10 13:32 UTC, phoerious commented
stfu, commit lint.

2020-12-10 13:44 UTC, myii requested changes
Thanks for this contribution, @phoerious.  I'm not marking this as `Request changes` because of anything you need to do but it's just that [Travis CI](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) decided to [suspend all of our jobs](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works) so all testing and `semantic-release` aren't running for any of our repos at the moment.  That's especially important for this PR since it also involves a `BREAKING CHANGE`.  We're close to replacing Travis with GitLab CI, so it shouldn't be too long.

In terms of the `BREAKING CHANGE` message itself, we've never tried a multiple line message, we usually use the same paragraph.  I'd be interested in testing this out locally first, to make sure all of the details you've provided actually make it through to the changelog and release notes.  If it doesn't, we'll have to adjust your commit message, even if it's done by us when merging this PR.

Thanks for your patience!

2020-12-10 13:52 UTC, myii commented
While we're waiting for the CI replacement, let's see if we can get any feedback about this PR from previous contributors.

---

@jle35 @teeuwes Since you provided some of the last PRs for this formula, I'm assuming you have some familiarity with it.  It involves a `BREAKING CHANGE` so it would be useful to find out how this PR would affect you.  Would you mind having a quick look here?  The PR has a small changeset.

2020-12-10 13:59 UTC, phoerious commented
The worst thing that can happen right now is that your deployment enables the Consul UI where it isn't supposed to. It's not possible to prevent this potential kind of side effect, but the other way round would be much worse.

2020-12-10 14:17 UTC, myii commented
For reference purposes:

https://www.consul.io/docs/agent/options.html#ui-1

> ui_config - This object allows a number of sub-keys to be set which controls the display or features available in the UI. Configuring the UI with this stanza was added in Consul 1.9.0.
> 
> The following sub-keys are available:
> 
> * enabled - This enables the service of the web UI from this agent. Boolean value, defaults to false. In -dev mode this defaults to true. Replaces ui from before 1.9.0. Equivalent to the -ui command-line flag.
> * ...

2020-12-11 15:23 UTC, myii commented
@phoerious So I've got GitLab CI running in my fork and I'll be bringing it over here fairly soon.  In the meantime, I used it to test out how the commit message would be rendered in the changelog and this is what is produced:

* https://github.com/myii/consul-formula/blob/master/docs/CHANGELOG.rst#100-2020-12-11
  - (Note for posterity: this link will probably break after some time, when I "fix" my local fork of this formula to match the GitLab CI that will be set up here).

I tried a few different options, which you can see above that entry.  The commit message I used each time is linked.  The [last attempt](https://github.com/myii/consul-formula/blob/master/docs/CHANGELOG.rst#500-2020-12-11) is probably the one I propose to use for the commit message here.  It formats the eventual result to be easier to read, hopefully.

2020-12-11 15:37 UTC, myii commented
@phoerious Also worth mentioning that your changes passed the CI testing that usually runs here:

* https://gitlab.com/myii/consul-formula/-/pipelines/228257579

2020-12-11 16:39 UTC, phoerious commented
Use whatever commit message you prefer. I only put it there for your information. It's in the PR description as well.

2020-12-13 18:56 UTC, merged

2020-12-13 18:57 UTC, myii commented
Merged, thanks @phoerious.