feat(map): update to v5 `map.jinja`
saltstack-formulas/consul-formula pull request #55
Opened 2022-04-22 03:55 UTC by sticky-note

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

### What type of PR is this?

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

### Describe the changes you're proposing

update to v5 `map.jinja`

### Pillar / config required to test the proposed changes

### Debug log showing how the proposed changes work

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### Additional context

2022-04-25 06:29 UTC, sticky-note commented
@myii : I've just rebase this with new master

2022-04-25 07:59 UTC, myii requested changes
Only a quick review for now but there is one glaring problem, as mentioned inline.

Otherwise, the `map.jinja` verifier has really helped a lot to confirm that the v5 update appears to have been implemented correctly!

2022-04-25 07:59 UTC, myii commented on consul/config.sls
> +{%- from tplroot ~ "/map.jinja" import mapdata with context %}
Looks like this was pasted by mistake.

2022-04-25 09:21 UTC, sticky-note commented on consul/config.sls
> +{%- from tplroot ~ "/map.jinja" import mapdata with context %}
oups, sorry for the paste mistake  :-1:

2022-04-25 09:22 UTC, sticky-note commented on consul/config.sls
> +{%- from tplroot ~ "/map.jinja" import mapdata with context %}
@myii Updated the request

2022-04-26 03:36 UTC, sticky-note commented
@myii PR seems to be ok now

2022-04-27 05:28 UTC, myii requested changes
Almost there, @sticky-note.  One change mentioned inline (below) and one more here.

https://github.com/saltstack-formulas/consul-formula/blob/ce35c1ca66b015190a8d671e8dd0e56faeed97c5/CODEOWNERS#L21-L26

This needs to be adjusted in this way;

```diff
 /docs/TOFS_pattern.rst                      @saltstack-formulas/ssf
 /*/_mapdata/                                @saltstack-formulas/ssf
+/*/libmapstack.jinja                        @saltstack-formulas/ssf
+/*/libmatchers.jinja                        @saltstack-formulas/ssf
 /*/libsaltcli.jinja                         @saltstack-formulas/ssf
 /*/libtofs.jinja                            @saltstack-formulas/ssf
+/*/map.jinja                                @saltstack-formulas/ssf
 /test/integration/**/_mapdata.rb            @saltstack-formulas/ssf
 /test/integration/**/libraries/system.rb    @saltstack-formulas/ssf
```

---

Checked with https://github.com/myii/ssf-formula/pull/434.

2022-04-27 05:28 UTC, myii commented on consul/libtofs.jinja
> +{%- macro files_switch(
This macro is unused for this particular PR, so please remove this file for now (and add it in #58).  Also, `docs/TOFS_pattern.rst` should also be added in #58 as well.

2022-04-27 06:00 UTC, sticky-note commented
@myii Requested changes are done.

2022-04-27 15:24 UTC, myii approved these changes

2022-04-27 15:25 UTC, merged

2022-04-27 15:25 UTC, myii commented
Fantastic work, @sticky-note -- merged, thanks for the patience.